In [1]:
from src.lesson_00.functions import load_data
from pathlib import Path

In [2]:
DATA = Path("../../data/raw/annual_peak_flow.csv")
df = load_data(DATA)

Dataset has been loaded as a Pandas Dataframe

In [3]:
df.head()

   year  peak_flow_cfs
0  2005            412
1  2006            437
2  2007            455
3  2008            472
4  2009            489

In [4]:
df.tail()

    year  peak_flow_cfs
15  2020            691
16  2021            724
17  2022            771
18  2023            845
19  2024            936

In [5]:
print(df.dtypes)

year             int64
peak_flow_cfs    int64
dtype: object